osx_image: xcode9.1
language: objective-c
branches:
  only:
    - master
cache:
    directories:
        - Carthage
before_install:
    - gem install xcpretty
    - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
before_script:
    - set -o pipefail
script:
    - xcodebuild test -workspace ./HakoBus-v2.xcworkspace -scheme HakoBus-v2Tests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.3.1,name=iPhone 7' | xcpretty -c